# Generated by Django 5.0.6 on 2024-06-21 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photos",
            new_name="Photo",
        ),
    ]
